#!/bin/bash

# setup-automated-scanning.sh

# OJS Security Scanner - Automated Setup Script

set -e

echo "OJS Security Scanner - Automated Scanning Setup"
echo "================================================"
echo ""

# ==================================================

# CHECK PYTHON

# ==================================================

if ! command -v python3 >/dev/null 2>&1; then
echo "[ERROR] Python3 not found."
exit 1
fi

PYTHON_VERSION=$(python3 --version 2>&1)
echo "[OK] Python version: $PYTHON_VERSION"
echo ""

# ==================================================

# LLM CONFIGURATION

# ==================================================

echo "LLM Configuration"
echo "-----------------"

read -p "OpenAI API Key (optional): " LLM_API_KEY

echo ""

# ==================================================

# SMTP CONFIGURATION

# ==================================================

echo "Email Configuration (SMTP)"
echo "--------------------------"

read -p "SMTP Server (default: smtp.gmail.com): " SMTP_SERVER
SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}

read -p "SMTP Port (default: 587): " SMTP_PORT
SMTP_PORT=${SMTP_PORT:-587}

read -p "SMTP Username / Sender Email: " SMTP_USERNAME

read -sp "SMTP Password / App Password: " SMTP_PASSWORD
echo ""

read -p "Report Recipient Email: " REPORT_RECIPIENT

echo ""

# ==================================================

# SCHEDULER CONFIGURATION

# ==================================================

echo "Scheduler Configuration"
echo "-----------------------"

read -p "Scan Interval (hours, default: 6): " SCAN_INTERVAL_HOURS
SCAN_INTERVAL_HOURS=${SCAN_INTERVAL_HOURS:-6}

read -p "Enable Scheduler (true/false, default: true): " ENABLE_SCHEDULER
ENABLE_SCHEDULER=${ENABLE_SCHEDULER:-true}

echo ""

# ==================================================

# OJS CONFIGURATION

# ==================================================

echo "OJS Configuration"
echo "-----------------"

read -p "OJS Source Path (default: ojs/ojs-main): " OJS_SOURCE_PATH
OJS_SOURCE_PATH=${OJS_SOURCE_PATH:-ojs/ojs-main}

echo ""

# ==================================================

# GENERATE .ENV

# ==================================================

echo "Generating .env file..."
echo ""

cat > .env << EOF

# ==========================================

# OJS SECURITY SCANNER CONFIGURATION

# Generated by setup-automated-scanning.sh

# ==========================================

# LLM Configuration

LLM_PROVIDER=openai
LLM_API_KEY=$LLM_API_KEY
LLM_MODEL=gpt-4o-mini
LLM_TIMEOUT=30

# Scanner Configuration

OJS_SOURCE_PATH=$OJS_SOURCE_PATH
SCANNER_OUTPUT_PATH=scan-output/latest.json
SEMGREP_ENABLED=true
SEMGREP_TIMEOUT_SECONDS=90

# Scheduler Configuration

ENABLE_SCHEDULER=$ENABLE_SCHEDULER
SCAN_INTERVAL_HOURS=$SCAN_INTERVAL_HOURS

# SMTP Configuration

SMTP_SERVER=$SMTP_SERVER
SMTP_PORT=$SMTP_PORT
SMTP_USERNAME=$SMTP_USERNAME
SMTP_PASSWORD=$SMTP_PASSWORD

# Report Configuration

REPORT_RECIPIENT=$REPORT_RECIPIENT
EOF

chmod 600 .env

echo "[OK] .env file created successfully"
echo ""

# ==================================================

# INSTALL DEPENDENCIES

# ==================================================

if [ -f requirements.txt ]; then
echo "Installing dependencies..."

if command -v pip >/dev/null 2>&1; then
    pip install -r requirements.txt
else
    python3 -m pip install -r requirements.txt
fi

echo "[OK] Dependencies installed"

else
echo "[WARNING] requirements.txt not found"
fi

echo ""

# ==================================================

# DATABASE INITIALIZATION

# ==================================================

if [ -d backend ]; then
echo "Initializing database..."


python3 << 'PYTHON_EOF'

try:
    from backend.database import engine, Base

    Base.metadata.create_all(bind=engine)

    print("[OK] Database initialized")

except Exception as e:
    print(f"[WARNING] Database initialization failed: {e}")

PYTHON_EOF

else
echo "[WARNING] backend directory not found"
fi

echo ""

# ==================================================

# COMPLETE

# ==================================================

echo "Setup Complete!"
echo ""
echo "Next Steps:"
echo "--------------------------------------"
echo "1. Verify the generated .env file"
echo ""
echo "2. Start the backend:"
echo "   python -m uvicorn backend.main:app --reload"
echo ""
echo "3. Register a user:"
echo "   curl -X POST 'http://localhost:8000/auth/register?username=admin&password=admin123'"
echo ""
echo "4. Configure report preferences:"
echo "   curl -X POST 'http://localhost:8000/auth/email-settings?token=YOUR_TOKEN'"
echo ""
echo "5. Check scheduler status:"
echo "   curl 'http://localhost:8000/scheduler/status'"
echo ""
echo "6. Run a manual scan test"
echo ""
echo "Configuration saved to .env"
echo "Documentation: SETUP_AUTOMATED_SCANNING.md"
