# setup-automated-scanning.ps1
# Quick setup script for automated scanning with email notifications (Windows)

Write-Host "OJS Security Scanner - Automated Scanning Setup" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

# Check Python version
$pythonVersion = python --version 2>&1
Write-Host "✓ Python version: $pythonVersion" -ForegroundColor Green
Write-Host ""

# Ask for SMTP Configuration
Write-Host "Email Configuration (SMTP)" -ForegroundColor Yellow
Write-Host "---"

$smtpServer = Read-Host "SMTP Server (default: smtp.gmail.com)"
if ([string]::IsNullOrWhiteSpace($smtpServer)) { $smtpServer = "smtp.gmail.com" }

$smtpPort = Read-Host "SMTP Port (default: 587)"
if ([string]::IsNullOrWhiteSpace($smtpPort)) { $smtpPort = "587" }

$senderEmail = Read-Host "Sender Email Address"

$senderPassword = Read-Host "Sender Email Password/App Password" -AsSecureString
$senderPasswordPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToCoTaskMemUnicode($senderPassword))

# Ask for Scheduler Configuration
Write-Host ""
Write-Host "Scheduler Configuration" -ForegroundColor Yellow
Write-Host "---"

$scanInterval = Read-Host "Scan Interval (hours, default: 6)"
if ([string]::IsNullOrWhiteSpace($scanInterval)) { $scanInterval = "6" }

$enableScheduler = Read-Host "Enable Scheduler (default: true)"
if ([string]::IsNullOrWhiteSpace($enableScheduler)) { $enableScheduler = "true" }

# Ask for OJS Path
Write-Host ""
$ojsSourcePath = Read-Host "OJS Source Path (default: ojs/ojs-main)"
if ([string]::IsNullOrWhiteSpace($ojsSourcePath)) { $ojsSourcePath = "ojs/ojs-main" }

Write-Host ""
Write-Host "Generating .env file..." -ForegroundColor Green
Write-Host ""

# Create or update .env file
$envContent = @(
"# OJS Security Scanner Configuration",
"# Generated by setup-automated-scanning.ps1",
"",
"# LLM Configuration",
"LLM_PROVIDER=openai",
"LLM_API_KEY=",
"LLM_MODEL=gpt-4o-mini",
"LLM_TIMEOUT=30",
"",
"# Scanner Configuration",
"OJS_SOURCE_PATH=$ojsSourcePath",
"SCANNER_OUTPUT_PATH=scan-output/latest.json",
"SEMGREP_ENABLED=true",
"SEMGREP_TIMEOUT_SECONDS=90",
"",
"# Automated Scanning & Scheduling (NEW)",
"ENABLE_SCHEDULER=$enableScheduler",
"SCAN_INTERVAL_HOURS=$scanInterval",
"",
"# Email Configuration (NEW)",
"SMTP_SERVER=$smtpServer",
"SMTP_PORT=$smtpPort",
"SENDER_EMAIL=$senderEmail",
"SENDER_PASSWORD=$senderPasswordPlain"
) -join "`r`n"

Set-Content -Path ".env" -Value $envContent -Encoding UTF8

Write-Host ".env file created successfully" -ForegroundColor Green
Write-Host ""

# Install/Update dependencies
Write-Host "Installing dependencies..." -ForegroundColor Green
pip install -r requirements.txt
Write-Host "Dependencies installed" -ForegroundColor Green
Write-Host ""

# Create database
Write-Host "Initializing database..." -ForegroundColor Green
python -c "from backend.database import engine, Base; Base.metadata.create_all(bind=engine); print('✓ Database initialized')"

Write-Host ""
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Start the application:"
Write-Host "   python -m uvicorn backend.main:app --reload"
Write-Host ""
Write-Host "2. Register a user:"
Write-Host "   curl -X POST 'http://localhost:8000/auth/register?username=admin&password=admin123'"
Write-Host ""
Write-Host "3. Configure email settings:"
$jsonExample = '{"email":"your-email@gmail.com","receive_reports":true}'

Write-Host "3. Configure email settings:"
Write-Host "   curl -X POST http://localhost:8000/auth/email-settings?token=YOUR_TOKEN -H 'Content-Type: application/json' -d '$jsonExample'"
Write-Host ""
Write-Host "4. Check scheduler status:"
Write-Host "   curl 'http://localhost:8000/scheduler/status'"
Write-Host ""
Write-Host "For detailed documentation, see: SETUP_AUTOMATED_SCANNING.md" -ForegroundColor Cyan
